apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    metadata.weave.works/dashboard.prometheus: https://prometheus.io/
    templates.weave.works/create-request: '{"repository_url":"https://github.com/ahsayde/wge-dev","head_branch":"wge-create-branch-ypqe6","title":"Creates
      resource prod-cluster","description":"This PR creates a cluster-template-development-prod
      instance","template_name":"cluster-template-development-prod","parameter_values":{"CLUSTER_NAME":"prod-cluster","CONTROL_PLANE_MACHINE_COUNT":"1","KUBERNETES_VERSION":"1.23.3","NAMESPACE":"default","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      cluster-template-development-prod instance","credentials":{},"values":[{"name":"cert-manager","version":"0.0.8","layer":"layer-0"}],"template_namespace":"default","template_kind":"CAPITemplate"}'
  labels:
    environment: prod
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/flux: bootstrap
  name: prod-cluster
  namespace: default
spec:
  capiClusterRef:
    name: prod-cluster

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    secretmanager: aws
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: prod-cluster-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: prod-cluster
    namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster
  namespace: default

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: prod-cluster-control-plane
      namespace: default
  replicas: 1
  version: 1.23.3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: cluster-template-development-prod
    templates.weave.works/template-namespace: default
  name: prod-cluster-md-0
  namespace: default
spec:
  clusterName: prod-cluster
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: prod-cluster-md-0
          namespace: default
      clusterName: prod-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: prod-cluster-md-0
        namespace: default
      version: 1.23.3
